### ISSUE TITLE
Address not displayed properly

### ISSUE THREAD

**Issue by efstratios** [volny/stylish-portfolio-jekyll#3]
Dear all,

I am trying to make a new website for a friend based  on your theme but i can't get the address to be displayed properly :-/ is there a specific way to write it on _config.yml file ? The address I want is : Themistokleous 64, 106 81 Athens, Greece here is my code : https://github.com/kavouras-rempetika

**Comment by volny** [comment]
You can separate your address per line, like so:

```
address:
  - line: Themistokleous 64
  - line: 106 81 Athens, Greece
```

or

```
address:
  - line: Themistokleous 64
  - line: 106 81 Athens
  - line: Greece
```

add as many lines as you want.
